{
 "title": "Sentiment API",
 "refresh": "10s",
 "panels": [
  {
   "title": "RPS (запросов в секунду)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{app_name=\"sentiment-analysis-api\"}[1m])",
     "legendFormat": "{{method}} {{handler}}"
    }
   ]
  },
  {
   "title": "Время ответа (p95, секунды)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{app_name=\"sentiment-analysis-api\"}[1m]))",
     "legendFormat": "p95 {{handler}}"
    }
   ]
  },
  {
   "title": "HTTP статусы",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_total{app_name=\"sentiment-analysis-api\"}[1m])",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Среднее время ответа (секунды)",
   "type": "stat",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{app_name=\"sentiment-analysis-api\"}[5m]) / rate(http_request_duration_seconds_count{app_name=\"sentiment-analysis-api\"}[5m])",
     "legendFormat": "avg latency"
    }
   ]
  }
 ]
}